// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_dp_legendre_matrix
Rcpp::NumericMatrix cpp_dp_legendre_matrix(Rcpp::NumericVector x, const int l_max);
RcppExport SEXP _dpgof_cpp_dp_legendre_matrix(SEXP xSEXP, SEXP l_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type l_max(l_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dp_legendre_matrix(x, l_max));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dp_projection_cdf_legendre_matrix
Rcpp::NumericMatrix cpp_dp_projection_cdf_legendre_matrix(Rcpp::NumericMatrix x_matrix, Rcpp::NumericVector r, Rcpp::NumericVector coefficients, const bool enforce_bounds);
RcppExport SEXP _dpgof_cpp_dp_projection_cdf_legendre_matrix(SEXP x_matrixSEXP, SEXP rSEXP, SEXP coefficientsSEXP, SEXP enforce_boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x_matrix(x_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type coefficients(coefficientsSEXP);
    Rcpp::traits::input_parameter< const bool >::type enforce_bounds(enforce_boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dp_projection_cdf_legendre_matrix(x_matrix, r, coefficients, enforce_bounds));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dp_normal_profile
Rcpp::NumericVector cpp_dp_normal_profile(Rcpp::NumericVector omega, Rcpp::NumericVector t_values, const double mu, const double sigma);
RcppExport SEXP _dpgof_cpp_dp_normal_profile(SEXP omegaSEXP, SEXP t_valuesSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_values(t_valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dp_normal_profile(omega, t_values, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dp_normal_profile_matrix
Rcpp::NumericMatrix cpp_dp_normal_profile_matrix(Rcpp::NumericVector omega, Rcpp::NumericMatrix t_matrix, const double mu, const double sigma);
RcppExport SEXP _dpgof_cpp_dp_normal_profile_matrix(SEXP omegaSEXP, SEXP t_matrixSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type t_matrix(t_matrixSEXP);
    Rcpp::traits::input_parameter< const double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dp_normal_profile_matrix(omega, t_matrix, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dp_weighted_sample_profile_rows
Rcpp::NumericMatrix cpp_dp_weighted_sample_profile_rows(Rcpp::IntegerMatrix order_matrix, Rcpp::IntegerMatrix rank_matrix, Rcpp::NumericVector normalized_weights);
RcppExport SEXP _dpgof_cpp_dp_weighted_sample_profile_rows(SEXP order_matrixSEXP, SEXP rank_matrixSEXP, SEXP normalized_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type order_matrix(order_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type rank_matrix(rank_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type normalized_weights(normalized_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dp_weighted_sample_profile_rows(order_matrix, rank_matrix, normalized_weights));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dp_weighted_sample_profile_linear
Rcpp::NumericMatrix cpp_dp_weighted_sample_profile_linear(Rcpp::IntegerMatrix order_matrix, Rcpp::IntegerVector rank_linear_index, Rcpp::NumericVector normalized_weights);
RcppExport SEXP _dpgof_cpp_dp_weighted_sample_profile_linear(SEXP order_matrixSEXP, SEXP rank_linear_indexSEXP, SEXP normalized_weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type order_matrix(order_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type rank_linear_index(rank_linear_indexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type normalized_weights(normalized_weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dp_weighted_sample_profile_linear(order_matrix, rank_linear_index, normalized_weights));
    return rcpp_result_gen;
END_RCPP
}
// cpp_profile_lookup_tensor_local_polynomial
Rcpp::NumericMatrix cpp_profile_lookup_tensor_local_polynomial(Rcpp::NumericMatrix values, Rcpp::NumericVector t_grid, Rcpp::NumericVector geometry_grid, Rcpp::NumericVector kappa_grid, Rcpp::NumericVector t_query, Rcpp::NumericVector geometry_query, Rcpp::NumericVector kappa_query, const int stencil_size);
RcppExport SEXP _dpgof_cpp_profile_lookup_tensor_local_polynomial(SEXP valuesSEXP, SEXP t_gridSEXP, SEXP geometry_gridSEXP, SEXP kappa_gridSEXP, SEXP t_querySEXP, SEXP geometry_querySEXP, SEXP kappa_querySEXP, SEXP stencil_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_grid(t_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type geometry_grid(geometry_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type kappa_grid(kappa_gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_query(t_querySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type geometry_query(geometry_querySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type kappa_query(kappa_querySEXP);
    Rcpp::traits::input_parameter< const int >::type stencil_size(stencil_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_profile_lookup_tensor_local_polynomial(values, t_grid, geometry_grid, kappa_grid, t_query, geometry_query, kappa_query, stencil_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fast_sample_ks_cvm_stats
Rcpp::List cpp_fast_sample_ks_cvm_stats(Rcpp::NumericMatrix centered_weights, Rcpp::NumericMatrix score_block, Rcpp::IntegerMatrix obs_order_matrix, Rcpp::IntegerMatrix tie_end_matrix, Rcpp::NumericMatrix correction_matrix, const double scale_factor, const bool compute_ks, const bool compute_cvm);
RcppExport SEXP _dpgof_cpp_fast_sample_ks_cvm_stats(SEXP centered_weightsSEXP, SEXP score_blockSEXP, SEXP obs_order_matrixSEXP, SEXP tie_end_matrixSEXP, SEXP correction_matrixSEXP, SEXP scale_factorSEXP, SEXP compute_ksSEXP, SEXP compute_cvmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type centered_weights(centered_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type score_block(score_blockSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type obs_order_matrix(obs_order_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type tie_end_matrix(tie_end_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type correction_matrix(correction_matrixSEXP);
    Rcpp::traits::input_parameter< const double >::type scale_factor(scale_factorSEXP);
    Rcpp::traits::input_parameter< const bool >::type compute_ks(compute_ksSEXP);
    Rcpp::traits::input_parameter< const bool >::type compute_cvm(compute_cvmSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fast_sample_ks_cvm_stats(centered_weights, score_block, obs_order_matrix, tie_end_matrix, correction_matrix, scale_factor, compute_ks, compute_cvm));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fast_sample_ks_cvm_stats_contiguous_double
Rcpp::List cpp_fast_sample_ks_cvm_stats_contiguous_double(Rcpp::NumericMatrix centered_weights, Rcpp::NumericMatrix score_block, Rcpp::IntegerMatrix obs_order_matrix, Rcpp::IntegerMatrix tie_end_matrix, Rcpp::NumericMatrix correction_matrix, const double scale_factor, const bool compute_ks, const bool compute_cvm);
RcppExport SEXP _dpgof_cpp_fast_sample_ks_cvm_stats_contiguous_double(SEXP centered_weightsSEXP, SEXP score_blockSEXP, SEXP obs_order_matrixSEXP, SEXP tie_end_matrixSEXP, SEXP correction_matrixSEXP, SEXP scale_factorSEXP, SEXP compute_ksSEXP, SEXP compute_cvmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type centered_weights(centered_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type score_block(score_blockSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type obs_order_matrix(obs_order_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type tie_end_matrix(tie_end_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type correction_matrix(correction_matrixSEXP);
    Rcpp::traits::input_parameter< const double >::type scale_factor(scale_factorSEXP);
    Rcpp::traits::input_parameter< const bool >::type compute_ks(compute_ksSEXP);
    Rcpp::traits::input_parameter< const bool >::type compute_cvm(compute_cvmSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fast_sample_ks_cvm_stats_contiguous_double(centered_weights, score_block, obs_order_matrix, tie_end_matrix, correction_matrix, scale_factor, compute_ks, compute_cvm));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sunspots_joint_profile_block
Rcpp::NumericMatrix cpp_sunspots_joint_profile_block(Rcpp::NumericMatrix radii, Rcpp::NumericVector rho, Rcpp::NumericVector center_s, Rcpp::NumericVector time_nodes, Rcpp::NumericVector time_weights, Rcpp::NumericMatrix coefficients);
RcppExport SEXP _dpgof_cpp_sunspots_joint_profile_block(SEXP radiiSEXP, SEXP rhoSEXP, SEXP center_sSEXP, SEXP time_nodesSEXP, SEXP time_weightsSEXP, SEXP coefficientsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type center_s(center_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_nodes(time_nodesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_weights(time_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type coefficients(coefficientsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sunspots_joint_profile_block(radii, rho, center_s, time_nodes, time_weights, coefficients));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sunspots_joint_profile_block_sorted
Rcpp::NumericMatrix cpp_sunspots_joint_profile_block_sorted(Rcpp::NumericMatrix radii, Rcpp::NumericVector rho, Rcpp::NumericVector center_s, Rcpp::NumericVector time_nodes, Rcpp::NumericVector time_weights, Rcpp::NumericMatrix coefficients);
RcppExport SEXP _dpgof_cpp_sunspots_joint_profile_block_sorted(SEXP radiiSEXP, SEXP rhoSEXP, SEXP center_sSEXP, SEXP time_nodesSEXP, SEXP time_weightsSEXP, SEXP coefficientsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type center_s(center_sSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_nodes(time_nodesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_weights(time_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type coefficients(coefficientsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sunspots_joint_profile_block_sorted(radii, rho, center_s, time_nodes, time_weights, coefficients));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dpgof_cpp_dp_legendre_matrix", (DL_FUNC) &_dpgof_cpp_dp_legendre_matrix, 2},
    {"_dpgof_cpp_dp_projection_cdf_legendre_matrix", (DL_FUNC) &_dpgof_cpp_dp_projection_cdf_legendre_matrix, 4},
    {"_dpgof_cpp_dp_normal_profile", (DL_FUNC) &_dpgof_cpp_dp_normal_profile, 4},
    {"_dpgof_cpp_dp_normal_profile_matrix", (DL_FUNC) &_dpgof_cpp_dp_normal_profile_matrix, 4},
    {"_dpgof_cpp_dp_weighted_sample_profile_rows", (DL_FUNC) &_dpgof_cpp_dp_weighted_sample_profile_rows, 3},
    {"_dpgof_cpp_dp_weighted_sample_profile_linear", (DL_FUNC) &_dpgof_cpp_dp_weighted_sample_profile_linear, 3},
    {"_dpgof_cpp_profile_lookup_tensor_local_polynomial", (DL_FUNC) &_dpgof_cpp_profile_lookup_tensor_local_polynomial, 8},
    {"_dpgof_cpp_fast_sample_ks_cvm_stats", (DL_FUNC) &_dpgof_cpp_fast_sample_ks_cvm_stats, 8},
    {"_dpgof_cpp_fast_sample_ks_cvm_stats_contiguous_double", (DL_FUNC) &_dpgof_cpp_fast_sample_ks_cvm_stats_contiguous_double, 8},
    {"_dpgof_cpp_sunspots_joint_profile_block", (DL_FUNC) &_dpgof_cpp_sunspots_joint_profile_block, 6},
    {"_dpgof_cpp_sunspots_joint_profile_block_sorted", (DL_FUNC) &_dpgof_cpp_sunspots_joint_profile_block_sorted, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_dpgof(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
