# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dp_legendre_matrix <- function(x, l_max) {
    .Call(`_gofmetric_cpp_dp_legendre_matrix`, x, l_max)
}

cpp_dp_projection_cdf_legendre_matrix <- function(x_matrix, r, coefficients, enforce_bounds = TRUE) {
    .Call(`_gofmetric_cpp_dp_projection_cdf_legendre_matrix`, x_matrix, r, coefficients, enforce_bounds)
}

cpp_dp_normal_profile <- function(omega, t_values, mu, sigma) {
    .Call(`_gofmetric_cpp_dp_normal_profile`, omega, t_values, mu, sigma)
}

cpp_dp_normal_profile_matrix <- function(omega, t_matrix, mu, sigma) {
    .Call(`_gofmetric_cpp_dp_normal_profile_matrix`, omega, t_matrix, mu, sigma)
}

cpp_dp_weighted_sample_profile_rows <- function(order_matrix, rank_matrix, normalized_weights) {
    .Call(`_gofmetric_cpp_dp_weighted_sample_profile_rows`, order_matrix, rank_matrix, normalized_weights)
}

cpp_dp_weighted_sample_profile_linear <- function(order_matrix, rank_linear_index, normalized_weights) {
    .Call(`_gofmetric_cpp_dp_weighted_sample_profile_linear`, order_matrix, rank_linear_index, normalized_weights)
}

cpp_profile_lookup_tensor_local_polynomial <- function(values, t_grid, geometry_grid, kappa_grid, t_query, geometry_query, kappa_query, stencil_size = 6L) {
    .Call(`_gofmetric_cpp_profile_lookup_tensor_local_polynomial`, values, t_grid, geometry_grid, kappa_grid, t_query, geometry_query, kappa_query, stencil_size)
}

cpp_fast_sample_ks_cvm_stats <- function(centered_weights, score_block, obs_order_matrix, tie_end_matrix, correction_matrix, scale_factor, compute_ks = TRUE, compute_cvm = TRUE) {
    .Call(`_gofmetric_cpp_fast_sample_ks_cvm_stats`, centered_weights, score_block, obs_order_matrix, tie_end_matrix, correction_matrix, scale_factor, compute_ks, compute_cvm)
}

cpp_fast_sample_ks_cvm_stats_contiguous_double <- function(centered_weights, score_block, obs_order_matrix, tie_end_matrix, correction_matrix, scale_factor, compute_ks = TRUE, compute_cvm = TRUE) {
    .Call(`_gofmetric_cpp_fast_sample_ks_cvm_stats_contiguous_double`, centered_weights, score_block, obs_order_matrix, tie_end_matrix, correction_matrix, scale_factor, compute_ks, compute_cvm)
}

cpp_sunspots_joint_profile_block <- function(radii, rho, center_s, time_nodes, time_weights, coefficients) {
    .Call(`_gofmetric_cpp_sunspots_joint_profile_block`, radii, rho, center_s, time_nodes, time_weights, coefficients)
}

cpp_sunspots_joint_profile_block_sorted <- function(radii, rho, center_s, time_nodes, time_weights, coefficients) {
    .Call(`_gofmetric_cpp_sunspots_joint_profile_block_sorted`, radii, rho, center_s, time_nodes, time_weights, coefficients)
}

